# -*- coding: utf-8 -*-
"""GS_CognitiveComputing_EnzoCampos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYDlVbsXdMI42VPu_Bmw-pKW0_vsArXi

#Global Solution Cognitive Computing, Computer Vision and IoT Systems
Prof. Arnaldo Viana



# Predição de Sucesso em Missões Espaciais Utilizando Machine Learning

## Integrante
Enzo Campos – RM 552006

## Objetivo
Desenvolver um modelo de Machine Learning capaz de prever o sucesso de missões espaciais utilizando dados históricos de lançamentos.

##Fonte Utilizada
https://www.kaggle.com/datasets/agirlcoding/all-space-missions-from-1957/data


##Resultado

A análise exploratória mostrou que a maior parte dos lançamentos espaciais registrados foi realizada por grandes organizações governamentais e empresas do setor aeroespacial.

Tambem foi possível identificar os países com maior numero de lançamentos, destacando Rússia, Eua e Cazaquistão como os principais participantes da atividade espacial historica.

Após o treinamento do modelo Random Forest, a matriz de confusão demonstrou que o modelo identificou corretamente 1.152 missões bem sucedidas, apresentando otimo desempenho para previsão de sucessos.

A base de dados é desbalanceada, contendo aproximadamente 90% de missões bem sucedidas e apenas 10% de falhas, o que impactou a capacidade do modelo em identificar missões fracassadas.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Space_Corrected.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

plt.figure(figsize=(12,6))

df['Company Name'].value_counts().head(10).plot(kind='bar')

plt.title('Empresas com mais lançamentos')
plt.show()

df['Country'] = df['Location'].apply(
    lambda x: str(x).split(',')[-1].strip()
)

country_launches = df['Country'].value_counts().head(15)

print(country_launches)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

country_launches.plot(kind='bar')

plt.title('Top 15 Países com Mais Lançamentos')
plt.xlabel('País')
plt.ylabel('Quantidade de Lançamentos')

plt.show()

df.columns = df.columns.str.strip()
df['Rocket'] = df['Rocket'].fillna(0)

df['Status Mission'].value_counts()

df['Sucesso'] = df['Status Mission'].apply(
    lambda x: 1 if x == 'Success' else 0
)

for coluna in df:
    print(df[coluna].value_counts())
df['Sucesso'].value_counts()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

dados = df[
    [
        'Company Name',
        'Location',
        'Status Rocket'
    ]
].copy()

encoder = LabelEncoder()

for coluna in dados.columns:
    dados[coluna] = encoder.fit_transform(
        dados[coluna].astype(str)
    )

X = dados

df['Sucesso'] = df['Status Mission'].apply(
    lambda x: 1 if x == 'Success' else 0
)

print("Quantidade de registros:", len(df))

print("\nDistribuição das missões:")
print(df['Status Mission'].value_counts())

print("\nDistribuição da variável alvo:")
print(df['Sucesso'].value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

from sklearn.ensemble import RandomForestClassifier

modelo = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

modelo.fit(X_train, y_train)

previsoes = modelo.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

acc = accuracy_score(
    y_test,
    previsoes
)

print("Acurácia:", acc)

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(
    y_test,
    previsoes
)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title('Matriz de Confusão')

plt.xlabel('Previsto')

plt.ylabel('Real')

plt.show()

print(classification_report(y_test, previsoes))